/* eslint-disable @typescript-eslint/ban-ts-comment */
// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.4 bubble.glb
*/

import React, { useRef } from "react";
import { useEnvironment, useGLTF } from "@react-three/drei";


import { useYuka } from "~/hooks/useYoka";


export const Bubble = (props, path, position, scale=1) => {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
  const [ref] = useYuka({ position });
  // eslint-disable-next-line @typescript-eslint/no-explicit-any, @typescript-eslint/no-unsafe-assignment

  const { nodes, materials } = useGLTF("/bubble_animation_02.glb");


  if (!ref) return <></>;

  return (
    <group {...props} dispose={null}>
      <mesh
        renderOrder={0}
        ref={ref}
        geometry={nodes.Sphere.geometry}
        material={materials["Material.001"]}
        scale={scale}
      />
      {/* <meshPhysicalMaterial
        attach="material"
        roughness={0}
        metalness={0}
      /> */}
      {/* <pointLight position={[0, 0, 0]} intensity={20} color="#fff" /> */}
      {/* <ambientLight intensity={100000} color="#ededde" /> */}
    </group>
  );
};

useGLTF.preload("/bubble.glb");
